version: '2'
services:
  client:
    container_name: weathr-client
    image: weathr_client:latest
    restart: always
    expose:
      - "3003"
    environment:
      VIRTUAL_HOST: wt.anclaev.com, www.wt.anclaev.com
      VIRTUAL_PORT: 3003
      CERT_NAME: anclaev.com
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
